-- Rakexura 2026 additive cutover migration.
-- Back up the database before running. Apply only when the Next.js app is ready.

create extension if not exists pgcrypto;

alter table public.games
  add column if not exists slug text,
  add column if not exists trailer_url text,
  add column if not exists price_history jsonb default '[]'::jsonb,
  add column if not exists minimum_requirements text,
  add column if not exists recommended_requirements text,
  add column if not exists activation_instructions text,
  add column if not exists activation_slots integer check (activation_slots is null or activation_slots >= 0);

alter table public.orders
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists order_reference text,
  add column if not exists payment_reference text,
  add column if not exists updated_at timestamptz default now();

alter table public.wishlist
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.cart_items
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.cart_bundles
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.wishlist add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.cart_items add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.cart_bundles add column if not exists user_id uuid references auth.users(id) on delete cascade;
create unique index if not exists wishlist_user_game_unique on public.wishlist(user_id, game_id) where user_id is not null;
create unique index if not exists cart_user_game_variant_unique on public.cart_items(user_id, game_id, variant_type) where user_id is not null;
create unique index if not exists cart_user_bundle_unique on public.cart_bundles(user_id, bundle_id) where user_id is not null;

create unique index if not exists orders_order_reference_key on public.orders(order_reference) where order_reference is not null;
create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists orders_customer_whatsapp_idx on public.orders(customer_whatsapp);
create index if not exists wishlist_user_id_idx on public.wishlist(user_id);
create index if not exists cart_items_user_id_idx on public.cart_items(user_id);
create index if not exists cart_bundles_user_id_idx on public.cart_bundles(user_id);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  whatsapp text,
  avatar_url text,
  role text not null default 'customer' check (role in ('customer', 'support', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_rewards (
  user_id uuid primary key references auth.users(id) on delete cascade,
  points integer not null default 0 check (points >= 0),
  level text not null default 'Bronze' check (level in ('Bronze', 'Silver', 'Gold', 'Diamond')),
  updated_at timestamptz not null default now()
);

create table if not exists public.reward_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  points integer not null,
  reason text not null,
  order_id bigint references public.orders(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text not null check (discount_type in ('percentage', 'flat')),
  discount_value numeric not null check (discount_value > 0),
  minimum_order numeric not null default 0,
  usage_limit integer,
  per_user_limit integer not null default 1,
  starts_at timestamptz default now(),
  expires_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.coupon_usage (
  id bigint generated by default as identity primary key,
  coupon_id bigint not null references public.coupons(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id bigint references public.orders(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references auth.users(id) on delete cascade,
  referred_id uuid unique references auth.users(id) on delete set null,
  code text not null unique,
  status text not null default 'pending' check (status in ('pending', 'qualified', 'rewarded')),
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  message text not null,
  type text not null default 'general',
  link text,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.game_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_name text not null check (char_length(game_name) between 2 and 120),
  platform text not null check (platform in ('Steam', 'Epic', 'Offline')),
  votes integer not null default 0,
  status text not null default 'requested' check (status in ('requested', 'reviewing', 'planned', 'available', 'declined')),
  created_at timestamptz not null default now()
);

create table if not exists public.game_votes (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.game_requests(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(request_id, user_id)
);

create or replace function public.refresh_game_request_votes()
returns trigger language plpgsql security definer set search_path = public
as $$ begin
  update public.game_requests set votes = (select count(*) from public.game_votes where request_id = coalesce(new.request_id, old.request_id)) where id = coalesce(new.request_id, old.request_id);
  return coalesce(new, old);
end; $$;

drop trigger if exists game_votes_refresh_count on public.game_votes;
create trigger game_votes_refresh_count after insert or delete on public.game_votes for each row execute function public.refresh_game_request_votes();

create table if not exists public.customer_library (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id bigint not null references public.games(id) on delete restrict,
  order_id bigint references public.orders(id) on delete set null,
  platform text,
  activation_guide text,
  delivery_notes text,
  purchased_at timestamptz not null default now(),
  unique(user_id, game_id, platform)
);

create table if not exists public.flash_sales (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  sale_price numeric not null check (sale_price >= 0),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id bigint references public.orders(id) on delete set null,
  subject text not null,
  message text not null,
  status text not null default 'open' check (status in ('open', 'in_progress', 'resolved', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  session_hash text not null,
  user_agent text,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.recent_deliveries (
  id bigint generated by default as identity primary key,
  order_id bigint unique not null references public.orders(id) on delete cascade,
  game_title text not null,
  delivered_at timestamptz not null default now(),
  public_label text not null
);

create table if not exists public.customer_proofs (
  id bigint generated by default as identity primary key,
  image_url text not null,
  caption text,
  proof_type text not null default 'testimonial' check (proof_type in ('whatsapp', 'payment', 'testimonial')),
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

create or replace function public.current_user_role()
returns text language sql stable security definer set search_path = public
as $$ select role from public.profiles where id = auth.uid() $$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin
  insert into public.profiles (id, display_name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1))) on conflict do nothing;
  insert into public.user_rewards (user_id) values (new.id) on conflict do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

drop function if exists public.create_store_order(text,text,jsonb,text);
drop function if exists public.create_store_order(text,text,jsonb,text,text,text);
drop function if exists public.create_store_order(text,text,jsonb,jsonb,text,text,text);

create or replace function public.create_store_order(
  p_customer_name text,
  p_customer_whatsapp text,
  p_items jsonb,
  p_bundles jsonb,
  p_payment_reference text default null,
  p_coupon_code text default null,
  p_payment_proof_path text default null
) returns text language plpgsql security definer set search_path = public
as $$
declare
  v_total numeric;
  v_bundle_total numeric := 0;
  v_id bigint;
  v_reference text;
  v_first_game bigint;
  v_recent_orders integer;
  v_coupon_id bigint;
  v_coupon_type text;
  v_coupon_value numeric;
  v_coupon_minimum numeric;
  v_coupon_usage_limit integer;
  v_coupon_per_user integer;
  v_coupon_uses integer;
  v_discount numeric := 0;
  v_valid_games integer := 0;
  v_valid_bundles integer := 0;
  v_cart_items jsonb := '[]'::jsonb;
begin
  if char_length(trim(p_customer_name)) < 2 then raise exception 'Customer name is required'; end if;
  if p_customer_whatsapp !~ '^[0-9]{10,15}$' then raise exception 'Invalid WhatsApp number'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_typeof(p_bundles) <> 'array' then raise exception 'Invalid cart'; end if;
  if jsonb_array_length(p_items) + jsonb_array_length(p_bundles) = 0
    or jsonb_array_length(p_items) + jsonb_array_length(p_bundles) > 20 then raise exception 'Invalid cart'; end if;

  select count(*) into v_recent_orders from public.orders
  where regexp_replace(customer_whatsapp, '[^0-9]', '', 'g') = p_customer_whatsapp
    and created_at > now() - interval '2 minutes';
  if v_recent_orders >= 3 then raise exception 'Too many recent orders. Please wait two minutes.'; end if;

  select coalesce(sum(case item->>'platform'
    when 'Epic' then g.epic_price
    when 'Offline' then g.offline_price
    else g.steam_price end * greatest(1, least(5, coalesce((item->>'quantity')::int, 1)))), 0), min(g.id), count(*)
  into v_total, v_first_game, v_valid_games
  from jsonb_array_elements(p_items) item
  join public.games g on g.id = (item->>'game_id')::bigint
  where coalesce(g.archived, false) = false
    and item->>'platform' = any(coalesce(g.available_platforms, array['Steam','Epic','Offline']));

  select coalesce(sum(b.bundle_price * greatest(1, least(5, coalesce((item->>'quantity')::int, 1)))), 0), count(*)
  into v_bundle_total, v_valid_bundles
  from jsonb_array_elements(p_bundles) item
  join public.bundles b on b.id = (item->>'bundle_id')::bigint
  where b.active = true;

  if v_valid_games <> jsonb_array_length(p_items) or v_valid_bundles <> jsonb_array_length(p_bundles) then
    raise exception 'One or more cart items are unavailable';
  end if;

  v_total := coalesce(v_total, 0) + coalesce(v_bundle_total, 0);
  if v_total <= 0 then raise exception 'Cart pricing could not be verified'; end if;

  if v_first_game is null then
    select min(bg.game_id) into v_first_game
    from jsonb_array_elements(p_bundles) item
    join public.bundle_games bg on bg.bundle_id = (item->>'bundle_id')::bigint;
  end if;

  select coalesce(jsonb_agg(line), '[]'::jsonb) into v_cart_items
  from (
    select jsonb_build_object(
      'type', 'game',
      'game_id', g.id,
      'title', g.title,
      'platform', item->>'platform',
      'quantity', greatest(1, least(5, coalesce((item->>'quantity')::int, 1))),
      'unit_price', case item->>'platform' when 'Epic' then g.epic_price when 'Offline' then g.offline_price else g.steam_price end
    ) as line
    from jsonb_array_elements(p_items) item
    join public.games g on g.id = (item->>'game_id')::bigint
    union all
    select jsonb_build_object(
      'type', 'bundle',
      'bundle_id', b.id,
      'title', b.title,
      'platform', 'Bundle',
      'quantity', greatest(1, least(5, coalesce((item->>'quantity')::int, 1))),
      'unit_price', b.bundle_price
    ) as line
    from jsonb_array_elements(p_bundles) item
    join public.bundles b on b.id = (item->>'bundle_id')::bigint
  ) verified_lines;

  if nullif(trim(p_coupon_code), '') is not null then
    select id, discount_type, discount_value, minimum_order, usage_limit, per_user_limit
    into v_coupon_id, v_coupon_type, v_coupon_value, v_coupon_minimum, v_coupon_usage_limit, v_coupon_per_user
    from public.coupons
    where upper(code) = upper(trim(p_coupon_code)) and active = true
      and (starts_at is null or starts_at <= now()) and (expires_at is null or expires_at > now());
    if v_coupon_id is null then raise exception 'Coupon is not active'; end if;
    if v_total < coalesce(v_coupon_minimum, 0) then raise exception 'Coupon minimum order is not met'; end if;
    select count(*) into v_coupon_uses from public.coupon_usage where coupon_id = v_coupon_id;
    if v_coupon_usage_limit is not null and v_coupon_uses >= v_coupon_usage_limit then raise exception 'Coupon usage limit reached'; end if;
    if auth.uid() is not null and v_coupon_per_user is not null and (select count(*) from public.coupon_usage where coupon_id = v_coupon_id and user_id = auth.uid()) >= v_coupon_per_user then raise exception 'Coupon already used'; end if;
    v_discount := least(v_total, case when v_coupon_type = 'percentage' then v_total * v_coupon_value / 100 else v_coupon_value end);
  end if;

  insert into public.orders (game_id, variant_type, customer_name, customer_whatsapp, payment_status, order_status, total_price, cart_items, user_id, payment_reference, screenshot_url)
  values (v_first_game, case when jsonb_array_length(p_items) + jsonb_array_length(p_bundles) > 1 then 'Multi-Game' when jsonb_array_length(p_bundles) = 1 then 'Bundle' else p_items->0->>'platform' end, trim(p_customer_name), p_customer_whatsapp, 'Pending', 'Pending', v_total - v_discount, v_cart_items, auth.uid(), nullif(trim(p_payment_reference), ''), nullif(trim(p_payment_proof_path), ''))
  returning id into v_id;
  v_reference := 'RKX-' || to_char(now(), 'YYMM') || '-' || lpad(v_id::text, 6, '0');
  update public.orders set order_reference = v_reference where id = v_id;
  if v_coupon_id is not null and auth.uid() is not null then insert into public.coupon_usage (coupon_id, user_id, order_id) values (v_coupon_id, auth.uid(), v_id); end if;
  return v_reference;
end; $$;

create or replace function public.track_store_order(p_order_reference text, p_phone_suffix text)
returns table(order_id bigint, order_ref text, status text, total_price numeric, created_at timestamptz, items jsonb)
language sql security definer set search_path = public
as $$
  select o.id, coalesce(o.order_reference, 'RKX-' || o.id), coalesce(o.order_status, o.payment_status, 'Pending'), o.total_price, o.created_at, coalesce(o.cart_items, '[]'::jsonb)
  from public.orders o
  where (o.order_reference = trim(p_order_reference) or o.id::text = regexp_replace(p_order_reference, '[^0-9]', '', 'g'))
    and right(regexp_replace(o.customer_whatsapp, '[^0-9]', '', 'g'), length(regexp_replace(p_phone_suffix, '[^0-9]', '', 'g'))) = regexp_replace(p_phone_suffix, '[^0-9]', '', 'g')
    and length(regexp_replace(p_phone_suffix, '[^0-9]', '', 'g')) >= 10
  limit 1;
$$;

revoke all on function public.create_store_order(text,text,jsonb,jsonb,text,text,text) from public;
grant execute on function public.create_store_order(text,text,jsonb,jsonb,text,text,text) to anon, authenticated;
revoke all on function public.track_store_order(text,text) from public;
grant execute on function public.track_store_order(text,text) to anon, authenticated;

alter table public.profiles enable row level security;
alter table public.user_rewards enable row level security;
alter table public.reward_transactions enable row level security;
alter table public.coupons enable row level security;
alter table public.coupon_usage enable row level security;
alter table public.referrals enable row level security;
alter table public.notifications enable row level security;
alter table public.game_requests enable row level security;
alter table public.game_votes enable row level security;
alter table public.customer_library enable row level security;
alter table public.flash_sales enable row level security;
alter table public.support_tickets enable row level security;
alter table public.customer_sessions enable row level security;
alter table public.recent_deliveries enable row level security;
alter table public.customer_proofs enable row level security;
alter table public.orders enable row level security;
alter table public.wishlist enable row level security;
alter table public.cart_items enable row level security;
alter table public.cart_bundles enable row level security;
alter table public.games enable row level security;
alter table public.bundles enable row level security;
alter table public.bundle_games enable row level security;
alter table public.reviews enable row level security;

alter table public.reviews
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists order_id bigint references public.orders(id) on delete set null,
  add column if not exists verified_purchase boolean not null default false,
  add column if not exists media_urls text[] not null default '{}';

create unique index if not exists reviews_user_game_unique
on public.reviews(user_id, game_id)
where user_id is not null;

create or replace function public.submit_verified_review(
  p_game_id bigint,
  p_rating integer,
  p_message text,
  p_media_urls text[] default '{}'
) returns bigint language plpgsql security definer set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_order_id bigint;
  v_review_id bigint;
  v_customer_name text;
begin
  if v_user is null then raise exception 'Sign in to review a purchase'; end if;
  if p_rating < 1 or p_rating > 5 then raise exception 'Rating must be between 1 and 5'; end if;
  if char_length(trim(p_message)) < 10 or char_length(trim(p_message)) > 1200 then
    raise exception 'Review must be between 10 and 1200 characters';
  end if;

  select o.id into v_order_id
  from public.orders o
  where o.user_id = v_user
    and lower(coalesce(o.order_status, o.payment_status, '')) in ('delivered', 'completed')
    and (
      o.game_id = p_game_id
      or exists (
        select 1 from jsonb_array_elements(coalesce(o.cart_items, '[]'::jsonb)) line
        where line->>'game_id' = p_game_id::text
      )
    )
  order by o.created_at desc
  limit 1;

  if v_order_id is null and not exists (
    select 1 from public.customer_library l where l.user_id = v_user and l.game_id = p_game_id
  ) then
    raise exception 'Only verified purchasers can review this game';
  end if;

  select coalesce(nullif(trim(display_name), ''), 'Verified customer') into v_customer_name
  from public.profiles where id = v_user;

  insert into public.reviews (game_id, customer_name, rating, message, approved, user_id, order_id, verified_purchase, media_urls)
  values (p_game_id, coalesce(v_customer_name, 'Verified customer'), p_rating, trim(p_message), false, v_user, v_order_id, true, coalesce(p_media_urls, '{}'))
  on conflict (user_id, game_id) where user_id is not null do update
    set rating = excluded.rating,
        message = excluded.message,
        order_id = excluded.order_id,
        verified_purchase = true,
        media_urls = excluded.media_urls,
        approved = false,
        created_at = now()
  returning id into v_review_id;

  return v_review_id;
end; $$;

revoke all on function public.submit_verified_review(bigint,integer,text,text[]) from public;
grant execute on function public.submit_verified_review(bigint,integer,text,text[]) to authenticated;

create or replace function public.handle_order_status_change()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  v_titles text;
begin
  if new.order_status is not distinct from old.order_status then return new; end if;

  if new.user_id is not null then
    insert into public.notifications (user_id, title, message, type, link)
    values (
      new.user_id,
      'Order ' || coalesce(new.order_reference, '#' || new.id),
      'Your order status is now ' || coalesce(new.order_status, 'updated') || '.',
      'order',
      '/dashboard/orders'
    );
  end if;

  if lower(coalesce(new.order_status, '')) in ('delivered', 'completed')
    and lower(coalesce(old.order_status, '')) not in ('delivered', 'completed') then
    if new.user_id is not null then
      insert into public.customer_library (user_id, game_id, order_id, platform, activation_guide, delivery_notes)
      select new.user_id, (line->>'game_id')::bigint, new.id, coalesce(line->>'platform', 'Steam'), g.activation_instructions, 'Delivered through Rakexura order ' || coalesce(new.order_reference, '#' || new.id)
      from jsonb_array_elements(coalesce(new.cart_items, '[]'::jsonb)) line
      join public.games g on g.id = (line->>'game_id')::bigint
      where line->>'type' = 'game'
      on conflict (user_id, game_id, platform) do nothing;

      insert into public.customer_library (user_id, game_id, order_id, platform, activation_guide, delivery_notes)
      select new.user_id, bg.game_id, new.id, 'Bundle', g.activation_instructions, 'Delivered in bundle order ' || coalesce(new.order_reference, '#' || new.id)
      from jsonb_array_elements(coalesce(new.cart_items, '[]'::jsonb)) line
      join public.bundle_games bg on bg.bundle_id = (line->>'bundle_id')::bigint
      join public.games g on g.id = bg.game_id
      where line->>'type' = 'bundle'
      on conflict (user_id, game_id, platform) do nothing;
    end if;

    select string_agg(line->>'title', ', ') into v_titles
    from jsonb_array_elements(coalesce(new.cart_items, '[]'::jsonb)) line;
    insert into public.recent_deliveries (order_id, game_title, public_label)
    values (new.id, coalesce(v_titles, 'Game order'), left(coalesce(new.customer_name, 'Customer'), 1) || '***')
    on conflict (order_id) do nothing;
  end if;

  return new;
end; $$;

drop trigger if exists on_order_status_change on public.orders;
create trigger on_order_status_change after update of order_status on public.orders
for each row execute procedure public.handle_order_status_change();

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notifications') then
    alter publication supabase_realtime add table public.notifications;
  end if;
exception when undefined_object then null;
end $$;

create policy "profiles read own" on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy "profiles update own" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid() and role = public.current_user_role());
create policy "rewards read own" on public.user_rewards for select using (user_id = auth.uid() or public.is_admin());
create policy "reward transactions read own" on public.reward_transactions for select using (user_id = auth.uid() or public.is_admin());
create policy "active coupons visible" on public.coupons for select using ((active and (expires_at is null or expires_at > now())) or public.is_admin());
create policy "coupon usage read own" on public.coupon_usage for select using (user_id = auth.uid() or public.is_admin());
create policy "referrals read own" on public.referrals for select using (referrer_id = auth.uid() or referred_id = auth.uid() or public.is_admin());
create policy "notifications read own" on public.notifications for select using (user_id = auth.uid() or public.is_admin());
create policy "notifications update own" on public.notifications for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "requests public read" on public.game_requests for select using (true);
create policy "requests insert own" on public.game_requests for insert with check (user_id = auth.uid());
create policy "votes insert own" on public.game_votes for insert with check (user_id = auth.uid());
create policy "votes delete own" on public.game_votes for delete using (user_id = auth.uid());
create policy "library read own" on public.customer_library for select using (user_id = auth.uid() or public.is_admin());
create policy "flash sales public read" on public.flash_sales for select using ((active and starts_at <= now() and ends_at > now()) or public.is_admin());
create policy "tickets own" on public.support_tickets for select using (user_id = auth.uid() or public.is_admin());
create policy "tickets insert own" on public.support_tickets for insert with check (user_id = auth.uid());
create policy "sessions own" on public.customer_sessions for select using (user_id = auth.uid() or public.is_admin());
create policy "recent deliveries public read" on public.recent_deliveries for select using (true);
create policy "approved proofs public read" on public.customer_proofs for select using (approved = true or public.is_admin());
create policy "proofs admin write" on public.customer_proofs for all using (public.is_admin()) with check (public.is_admin());
create policy "orders read own" on public.orders for select using (user_id = auth.uid() or public.is_admin());
create policy "admin manages orders" on public.orders for update using (public.is_admin()) with check (public.is_admin());
create policy "wishlist own rows" on public.wishlist for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "cart own rows" on public.cart_items for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "bundle cart own rows" on public.cart_bundles for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "games public read" on public.games for select using (coalesce(archived, false) = false or public.is_admin());
create policy "games admin write" on public.games for all using (public.is_admin()) with check (public.is_admin());
create policy "bundles public read" on public.bundles for select using (active = true or public.is_admin());
create policy "bundles admin write" on public.bundles for all using (public.is_admin()) with check (public.is_admin());
create policy "bundle games public read" on public.bundle_games for select using (true);
create policy "bundle games admin write" on public.bundle_games for all using (public.is_admin()) with check (public.is_admin());
create policy "reviews public approved read" on public.reviews for select using (approved = true or public.is_admin());
create policy "reviews admin moderate" on public.reviews for update using (public.is_admin()) with check (public.is_admin());
create policy "reviews admin delete" on public.reviews for delete using (public.is_admin());
create policy "public reads active games" on public.games for select using (coalesce(archived, false) = false or public.is_admin());
create policy "admin manages games" on public.games for all using (public.is_admin()) with check (public.is_admin());
create policy "public reads active bundles" on public.bundles for select using (active or public.is_admin());
create policy "admin manages bundles" on public.bundles for all using (public.is_admin()) with check (public.is_admin());
create policy "public reads bundle games" on public.bundle_games for select using (true);
create policy "admin manages bundle games" on public.bundle_games for all using (public.is_admin()) with check (public.is_admin());
create policy "public reads approved reviews" on public.reviews for select using (approved or public.is_admin());
create policy "admin manages reviews" on public.reviews for all using (public.is_admin()) with check (public.is_admin());
create policy "users manage own wishlist" on public.wishlist for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users manage own cart" on public.cart_items for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users manage own bundle cart" on public.cart_bundles for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Replace the legacy anonymous media upload policy with admin-only writes.
drop policy if exists "Public upload game images" on storage.objects;
drop policy if exists "Admin upload store media" on storage.objects;
create policy "Admin upload store media" on storage.objects for insert to authenticated
with check (bucket_id = 'game-images' and public.is_admin());
drop policy if exists "Admin update store media" on storage.objects;
create policy "Admin update store media" on storage.objects for update to authenticated
using (bucket_id = 'game-images' and public.is_admin()) with check (bucket_id = 'game-images' and public.is_admin());
drop policy if exists "Admin delete store media" on storage.objects;
create policy "Admin delete store media" on storage.objects for delete to authenticated
using (bucket_id = 'game-images' and public.is_admin());

-- Run this once after your account exists, replacing the email:
-- update public.profiles set role = 'admin' where id = (select id from auth.users where email = 'YOUR_EMAIL');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('payment-proofs', 'payment-proofs', false, 5242880, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy "customers upload payment proofs" on storage.objects for insert to anon, authenticated
with check (bucket_id = 'payment-proofs');
create policy "admins read payment proofs" on storage.objects for select to authenticated
using (bucket_id = 'payment-proofs' and public.is_admin());
create policy "customers remove failed payment proofs" on storage.objects for delete to anon, authenticated
using (bucket_id = 'payment-proofs' and owner_id = auth.uid()::text);
