-- Rakexura Phase 9: policy corrections and missing customer modules.
-- Apply after 202606210001_ultimate_rebuild.sql.

create table if not exists public.support_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 3000),
  is_staff boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.reward_offers (
  id bigint generated by default as identity primary key,
  title text not null,
  points_cost integer not null check (points_cost > 0),
  coupon_id bigint references public.coupons(id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.reward_redemptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  offer_id bigint not null references public.reward_offers(id) on delete restrict,
  points_spent integer not null check (points_spent > 0),
  created_at timestamptz not null default now()
);

alter table public.support_messages enable row level security;
alter table public.reward_offers enable row level security;
alter table public.reward_redemptions enable row level security;

drop policy if exists "admin manages coupons" on public.coupons;
create policy "admin manages coupons" on public.coupons for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin reads coupon usage" on public.coupon_usage;
create policy "admin reads coupon usage" on public.coupon_usage for select using (public.is_admin());
drop policy if exists "admin manages requests" on public.game_requests;
create policy "admin manages requests" on public.game_requests for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin manages votes" on public.game_votes;
create policy "admin manages votes" on public.game_votes for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin manages tickets" on public.support_tickets;
create policy "admin manages tickets" on public.support_tickets for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin manages notifications" on public.notifications;
create policy "admin manages notifications" on public.notifications for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin manages flash sales" on public.flash_sales;
create policy "admin manages flash sales" on public.flash_sales for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin manages library" on public.customer_library;
create policy "admin manages library" on public.customer_library for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin manages deliveries" on public.recent_deliveries;
create policy "admin manages deliveries" on public.recent_deliveries for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin deletes orders" on public.orders;
create policy "admin deletes orders" on public.orders for delete using (public.is_admin());

drop policy if exists "ticket participants read messages" on public.support_messages;
create policy "ticket participants read messages" on public.support_messages for select using (
  public.is_admin() or exists (select 1 from public.support_tickets t where t.id = ticket_id and t.user_id = auth.uid())
);
drop policy if exists "customers reply to own tickets" on public.support_messages;
create policy "customers reply to own tickets" on public.support_messages for insert to authenticated with check (
  user_id = auth.uid() and is_staff = false and exists (select 1 from public.support_tickets t where t.id = ticket_id and t.user_id = auth.uid())
);
drop policy if exists "admins reply to tickets" on public.support_messages;
create policy "admins reply to tickets" on public.support_messages for insert to authenticated with check (public.is_admin() and is_staff = true);

drop policy if exists "active reward offers visible" on public.reward_offers;
create policy "active reward offers visible" on public.reward_offers for select using (active or public.is_admin());
drop policy if exists "admin manages reward offers" on public.reward_offers;
create policy "admin manages reward offers" on public.reward_offers for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "users read own redemptions" on public.reward_redemptions;
create policy "users read own redemptions" on public.reward_redemptions for select using (user_id = auth.uid() or public.is_admin());

create or replace function public.redeem_reward_offer(p_offer_id bigint)
returns text language plpgsql security definer set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_cost integer;
  v_title text;
  v_coupon_code text;
  v_points integer;
begin
  if v_user is null then raise exception 'Sign in to redeem rewards'; end if;
  select o.points_cost, o.title, c.code into v_cost, v_title, v_coupon_code
  from public.reward_offers o left join public.coupons c on c.id = o.coupon_id
  where o.id = p_offer_id and o.active = true;
  if v_cost is null then raise exception 'Reward offer is unavailable'; end if;
  select points into v_points from public.user_rewards where user_id = v_user for update;
  if coalesce(v_points, 0) < v_cost then raise exception 'Not enough reward points'; end if;
  update public.user_rewards set points = points - v_cost, updated_at = now() where user_id = v_user;
  insert into public.reward_transactions (user_id, points, reason) values (v_user, -v_cost, 'Redeemed: ' || v_title);
  insert into public.reward_redemptions (user_id, offer_id, points_spent) values (v_user, p_offer_id, v_cost);
  insert into public.notifications (user_id, title, message, type, link)
  values (v_user, 'Reward redeemed', case when v_coupon_code is null then v_title else v_title || ' - coupon ' || v_coupon_code end, 'reward', '/dashboard/rewards');
  return coalesce(v_coupon_code, 'Reward redeemed');
end; $$;
revoke all on function public.redeem_reward_offer(bigint) from public;
grant execute on function public.redeem_reward_offer(bigint) to authenticated;

create or replace function public.claim_referral(p_code text)
returns text language plpgsql security definer set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_referral bigint;
  v_referrer uuid;
begin
  if v_user is null then raise exception 'Sign in to claim a referral'; end if;
  select id, referrer_id into v_referral, v_referrer from public.referrals
  where upper(code) = upper(trim(p_code)) and referred_id is null and status = 'pending' for update;
  if v_referral is null then raise exception 'Referral code is invalid or already claimed'; end if;
  if v_referrer = v_user then raise exception 'You cannot claim your own referral'; end if;
  if exists (select 1 from public.referrals where referred_id = v_user) then raise exception 'A referral is already linked to this account'; end if;
  update public.referrals set referred_id = v_user where id = v_referral;
  return 'Referral linked';
end; $$;
revoke all on function public.claim_referral(text) from public;
grant execute on function public.claim_referral(text) to authenticated;

create or replace function public.get_or_create_referral_code()
returns text language plpgsql security definer set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_code text;
begin
  if v_user is null then raise exception 'Sign in to create a referral code'; end if;
  select code into v_code from public.referrals where referrer_id = v_user order by created_at desc limit 1;
  if v_code is null then
    v_code := 'RKX-' || upper(substr(replace(v_user::text, '-', ''), 1, 8));
    insert into public.referrals (referrer_id, code) values (v_user, v_code);
  end if;
  return v_code;
end; $$;
revoke all on function public.get_or_create_referral_code() from public;
grant execute on function public.get_or_create_referral_code() to authenticated;

create or replace function public.sync_customer_store_state(p_items jsonb, p_bundles jsonb, p_wishlist jsonb)
returns void language plpgsql security definer set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_valid integer;
begin
  if v_user is null then raise exception 'Sign in to sync store data'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_typeof(p_bundles) <> 'array' or jsonb_typeof(p_wishlist) <> 'array' then raise exception 'Invalid store sync payload'; end if;
  if jsonb_array_length(p_items) > 100 or jsonb_array_length(p_bundles) > 50 or jsonb_array_length(p_wishlist) > 200 then raise exception 'Store sync limit exceeded'; end if;
  select count(*) into v_valid from jsonb_array_elements(p_items) item join public.games g on g.id = (item->>'game_id')::bigint
  where coalesce(g.archived, false) = false and item->>'platform' = any(coalesce(g.available_platforms, array['Steam','Epic','Offline']));
  if v_valid <> jsonb_array_length(p_items) then raise exception 'A cart game or platform is unavailable'; end if;
  select count(*) into v_valid from jsonb_array_elements(p_bundles) item join public.bundles b on b.id = (item->>'bundle_id')::bigint where b.active = true;
  if v_valid <> jsonb_array_length(p_bundles) then raise exception 'A cart bundle is unavailable'; end if;

  delete from public.cart_items where user_id = v_user;
  delete from public.cart_bundles where user_id = v_user;
  delete from public.wishlist where user_id = v_user;

  insert into public.cart_items (user_id, customer_identifier, game_id, variant_type, quantity)
  select v_user, v_user::text, (item->>'game_id')::bigint, item->>'platform', greatest(1, least(5, coalesce((item->>'quantity')::integer, 1)))
  from jsonb_array_elements(p_items) item;
  insert into public.cart_bundles (user_id, customer_identifier, bundle_id, quantity)
  select v_user, v_user::text, (item->>'bundle_id')::bigint, greatest(1, least(5, coalesce((item->>'quantity')::integer, 1)))
  from jsonb_array_elements(p_bundles) item;
  insert into public.wishlist (user_id, customer_identifier, game_id)
  select v_user, v_user::text, value::bigint from jsonb_array_elements_text(p_wishlist);
end; $$;
revoke all on function public.sync_customer_store_state(jsonb,jsonb,jsonb) from public;
grant execute on function public.sync_customer_store_state(jsonb,jsonb,jsonb) to authenticated;

create or replace function public.qualify_referral_after_delivery()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  v_referral public.referrals%rowtype;
begin
  if new.user_id is null or lower(coalesce(new.order_status, '')) not in ('delivered', 'completed')
    or lower(coalesce(old.order_status, '')) in ('delivered', 'completed') then return new; end if;
  select * into v_referral from public.referrals where referred_id = new.user_id and status = 'pending' limit 1 for update;
  if v_referral.id is null then return new; end if;
  update public.referrals set status = 'rewarded' where id = v_referral.id;
  insert into public.user_rewards (user_id, points) values (v_referral.referrer_id, 100) on conflict (user_id) do update set points = public.user_rewards.points + 100, updated_at = now();
  insert into public.user_rewards (user_id, points) values (new.user_id, 50) on conflict (user_id) do update set points = public.user_rewards.points + 50, updated_at = now();
  insert into public.reward_transactions (user_id, points, reason, order_id) values
    (v_referral.referrer_id, 100, 'Qualified referral reward', new.id),
    (new.user_id, 50, 'Welcome referral reward', new.id);
  return new;
end; $$;
drop trigger if exists qualify_referral_on_delivery on public.orders;
create trigger qualify_referral_on_delivery after update of order_status on public.orders
for each row execute procedure public.qualify_referral_after_delivery();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('review-media', 'review-media', false, 10485760, array['image/jpeg','image/png','image/webp','video/mp4'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
drop policy if exists "customers upload own review media" on storage.objects;
create policy "customers upload own review media" on storage.objects for insert to authenticated
with check (bucket_id = 'review-media' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "customers read own review media" on storage.objects;
create policy "customers read own review media" on storage.objects for select to authenticated
using (bucket_id = 'review-media' and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin()));
drop policy if exists "admins delete review media" on storage.objects;
create policy "admins delete review media" on storage.objects for delete to authenticated
using (bucket_id = 'review-media' and public.is_admin());

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'flash_sales') then
    alter publication supabase_realtime add table public.flash_sales;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'support_messages') then
    alter publication supabase_realtime add table public.support_messages;
  end if;
exception when undefined_object then null;
end $$;
