-- Rakexura Phase 10: admin media library and opt-in store updates.
-- Apply after 202606220001_phase9_security_and_modules.sql.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('game-images', 'game-images', true, 15728640, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admin upload store media" on storage.objects;
create policy "Admin upload store media" on storage.objects for insert to authenticated
with check (bucket_id = 'game-images' and public.is_admin());
drop policy if exists "Admin update store media" on storage.objects;
create policy "Admin update store media" on storage.objects for update to authenticated
using (bucket_id = 'game-images' and public.is_admin()) with check (bucket_id = 'game-images' and public.is_admin());
drop policy if exists "Admin delete store media" on storage.objects;
create policy "Admin delete store media" on storage.objects for delete to authenticated
using (bucket_id = 'game-images' and public.is_admin());

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique check (char_length(email) between 5 and 254),
  consented_at timestamptz not null default now(),
  active boolean not null default true
);
alter table public.newsletter_subscribers enable row level security;
drop policy if exists "visitors subscribe to updates" on public.newsletter_subscribers;
create policy "visitors subscribe to updates" on public.newsletter_subscribers for insert to anon, authenticated
with check (active = true);
drop policy if exists "admins manage subscribers" on public.newsletter_subscribers;
create policy "admins manage subscribers" on public.newsletter_subscribers for all to authenticated
using (public.is_admin()) with check (public.is_admin());
